# settings.yaml
# box_name: "sloopstash/ubuntu-22-04"
box_name: "bento/centos-stream-9"
# box_version: "2.1.1"
vm:
- name: "serverA"
  ip: "192.168.111.100"
  memory: "2048"
  cpus: "2"
- name: "serverB"
  ip: "192.168.111.200"
  memory: "2048"
  cpus: "2"
- name: "client"
  ip: "192.168.111.2"
  memory: "2048"
  cpus: "2"